### ISSUE TITLE
GASP doesn't work with nifty 1.2.1

### ISSUE THREAD

**Issue by bipashadey** [hci-unihd/plant-seg#107]
When I install plant seg on windows using anaconda python, it says nifty 1.0.9 not available. So I have installed the latest version of nifty i.e., nifty 1.2.1. But gasp gives an error on this however, multicast runs normally. Could you please help as to which nifty version I should install to run gasp successfully?

here is the error I get:
edge_indicators, edge_sizes = nrag.accumulate_affinities_mean_and_length(
AttributeError: module 'nifty.graph.rag' has no attribute 'accumulate_affinities_mean_and_length'

**Comment by lorenzocerrone** [comment]
Hi, this is a known issue currently plantseg is naively supported only on linux. But we are working to make it native for windows soon. 

See #101  for more info and updates!

**Comment by bipashadey** [comment]
sure. Thank you so much!

**Comment by lorenzocerrone** [comment]
Hi bipashadey,

We just finished fixing all compatibility issues. Now plantseg should fully work on windows.

Best regards,
Lorenzo
